export type Lesson = {
  number: number;
  title: string;
  area: 'Números' | 'Geometría' | 'Medición' | 'Información' | 'Azar';
  summary: string;
  explanation: string;
  example: string;
  steps: string[];
};

export type BookBlock = {
  id: number;
  numeral: string;
  label: string;
  description: string;
  goals: string[];
  lessons: Lesson[];
};

const lesson = (
  number: number,
  title: string,
  area: Lesson['area'],
  summary: string,
  explanation: string,
  example: string,
  steps: string[],
): Lesson => ({ number, title, area, summary, explanation, example, steps });

export const bookBlocks: BookBlock[] = [
  {
    id: 1,
    numeral: 'I',
    label: 'Números, cuerpos y tiempo',
    description:
      'Valor posicional, cálculo mental, multiplicación, cuerpos geométricos, reloj y lectura de información.',
    goals: [
      'Comparar y ordenar números de cuatro cifras.',
      'Restar mentalmente dígitos a múltiplos de 10.',
      'Obtener con rapidez productos de dígitos.',
      'Reconocer caras, aristas y vértices de cuerpos geométricos.',
      'Usar el reloj y obtener información de distintos portadores.',
    ],
    lessons: [
      lesson(
        1,
        'Agrupo en decenas, centenas y millares',
        'Números',
        'Comprende cómo se agrupan las unidades en el sistema decimal.',
        'Nuestro sistema de numeración agrupa de diez en diez: 10 unidades forman una decena, 10 decenas una centena y 10 centenas un millar. La posición de una cifra indica cuánto vale.',
        'En 3 649 hay 3 millares, 6 centenas, 4 decenas y 9 unidades: 3 000 + 600 + 40 + 9.',
        [
          'Cuenta o identifica todos los elementos.',
          'Forma grupos de 10 y cambia cada grupo por una decena.',
          'Repite el agrupamiento para formar centenas y millares.',
          'Escribe la cantidad según el valor de cada posición.',
        ],
      ),
      lesson(
        2,
        '¿Cuál tiene más elementos?',
        'Números',
        'Compara colecciones usando agrupamientos que facilitan el conteo.',
        'Una colección es más fácil de comparar cuando sus elementos se organizan en filas, grupos de diez o grupos iguales. No conviene decidir solo por el espacio que ocupa el dibujo.',
        'Una colección con 8 grupos de 10 y 6 elementos tiene 86. Otra con 7 grupos de 10 y 14 elementos también tiene 84; por eso la primera es mayor.',
        [
          'Organiza ambas colecciones de la misma manera.',
          'Cuenta primero los grupos completos.',
          'Suma los elementos que quedaron sueltos.',
          'Compara los totales con >, < o =.',
        ],
      ),
      lesson(
        3,
        'Regularidades en el cuadro numérico',
        'Números',
        'Descubre patrones al ordenar números en filas y columnas.',
        'En un cuadro numérico, al avanzar una casilla se suma 1; al retroceder se resta 1. Al bajar una fila normalmente se suma 10 y al subir se resta 10.',
        'Desde 47: a la derecha está 48, a la izquierda 46, debajo 57 y arriba 37.',
        [
          'Localiza un número de referencia.',
          'Observa si el movimiento es horizontal o vertical.',
          'Suma o resta 1 para columnas vecinas.',
          'Suma o resta 10 para filas vecinas.',
        ],
      ),
      lesson(
        4,
        'Restas con tarjetas',
        'Números',
        'Usa descomposiciones y complementos para restar mentalmente.',
        'Restar también significa buscar cuánto falta para llegar del sustraendo al minuendo. Descomponer un número permite trabajar primero con decenas y después con unidades.',
        'Para 52 - 8: de 8 a 10 faltan 2 y de 10 a 52 faltan 42; 2 + 42 = 44.',
        [
          'Identifica el número del que restas y cuánto quitarás.',
          'Busca una decena cercana para facilitar el cálculo.',
          'Completa por partes o descompón el sustraendo.',
          'Comprueba sumando el resultado y lo que restaste.',
        ],
      ),
      lesson(
        5,
        '¿Multiplicamos juguetes?',
        'Números',
        'Representa grupos iguales mediante multiplicaciones.',
        'La multiplicación permite sumar con rapidez una misma cantidad varias veces. Sus factores indican cuántos grupos hay y cuántos objetos contiene cada grupo.',
        'Cinco cajas con 6 juguetes cada una se representan como 5 × 6 = 30 juguetes.',
        [
          'Reconoce cuántos grupos iguales hay.',
          'Cuenta los elementos de un grupo.',
          'Multiplica número de grupos por elementos de cada grupo.',
          'Verifica mediante suma repetida o un arreglo rectangular.',
        ],
      ),
      lesson(
        6,
        'Cuerpos geométricos y sus elementos',
        'Geometría',
        'Reconoce caras, aristas y vértices en cuerpos geométricos.',
        'Los cuerpos geométricos ocupan espacio. Las caras pueden ser planas o curvas; las aristas son los bordes donde se unen caras y los vértices son las puntas donde coinciden aristas.',
        'Un cubo tiene 6 caras planas, 12 aristas y 8 vértices. Un cilindro tiene dos caras planas circulares y una cara curva.',
        [
          'Observa el cuerpo desde distintos lados.',
          'Señala y cuenta sus caras.',
          'Localiza los bordes o aristas.',
          'Cuenta los vértices y describe si hay superficies curvas.',
        ],
      ),
      lesson(
        7,
        '¿Los cuerpos geométricos son iguales o diferentes?',
        'Geometría',
        'Compara cuerpos a partir de sus características.',
        'Dos cuerpos pueden parecerse y, aun así, diferenciarse por la forma o cantidad de sus caras, aristas y vértices. Clasificarlos requiere observar sus propiedades, no solo su tamaño o color.',
        'Un cubo y un prisma rectangular tienen 6 caras, 12 aristas y 8 vértices, pero en el cubo todas las caras son cuadrados iguales.',
        [
          'Elige dos cuerpos para comparar.',
          'Registra la forma y cantidad de caras.',
          'Compara aristas, vértices y superficies curvas.',
          'Explica en qué se parecen y en qué son diferentes.',
        ],
      ),
      lesson(
        8,
        'Dibujo e imagino cuerpos geométricos',
        'Geometría',
        'Relaciona cuerpos tridimensionales con dibujos y descripciones.',
        'Un dibujo muestra solo una vista de un cuerpo. Para imaginarlo completo hay que considerar qué caras se ven, cuáles están ocultas y cómo se unen.',
        'Al dibujar un cubo se representan tres caras visibles; las líneas inclinadas ayudan a mostrar profundidad aunque todas sus aristas reales midan lo mismo.',
        [
          'Identifica la forma de las caras visibles.',
          'Imagina las caras que quedan detrás.',
          'Dibuja primero la cara frontal.',
          'Agrega profundidad y une los vértices correspondientes.',
        ],
      ),
      lesson(
        9,
        'Mi localidad',
        'Información',
        'Interpreta representaciones sencillas de lugares conocidos.',
        'Un plano o croquis representa un espacio visto desde arriba. Los símbolos muestran lugares importantes y las calles o caminos permiten relacionar posiciones.',
        'Si la escuela está frente al parque y la biblioteca a la derecha del parque, esas referencias permiten ubicar los tres lugares aunque el dibujo no tenga medidas exactas.',
        [
          'Identifica el punto de referencia principal.',
          'Reconoce símbolos, calles y lugares.',
          'Relaciona expresiones como frente a, junto a y entre.',
          'Describe una ruta siguiendo el orden de los lugares.',
        ],
      ),
      lesson(
        10,
        'El tiempo',
        'Medición',
        'Lee horas y minutos en relojes analógicos y digitales.',
        'En el reloj analógico, la manecilla corta indica la hora y la larga los minutos. Cada número recorrido por la manecilla larga representa 5 minutos.',
        'Si la manecilla corta está después del 3 y la larga en el 6, son las 3:30, es decir, las tres y media.',
        [
          'Observa primero la manecilla corta para identificar la hora.',
          'Cuenta de cinco en cinco con la manecilla larga.',
          'Une ambos datos: hora y minutos.',
          'Comprueba escribiendo la hora en formato digital.',
        ],
      ),
      lesson(
        11,
        '¿A qué hora termino?',
        'Medición',
        'Calcula horas de inicio, término y duración.',
        'Para medir un intervalo de tiempo se puede avanzar por horas completas y luego por minutos. Una hora equivale a 60 minutos.',
        'Una película comienza a las 4:25 y dura 1 hora 30 minutos: termina a las 5:55.',
        [
          'Anota la hora de inicio.',
          'Suma primero las horas completas.',
          'Suma los minutos restantes.',
          'Si llegas a 60 minutos, cámbialos por una hora.',
        ],
      ),
      lesson(
        12,
        'Obtengo más datos',
        'Información',
        'Deduce información a partir de datos presentados.',
        'Los anuncios, calendarios, boletos y tablas contienen datos explícitos y también permiten obtener datos nuevos al relacionarlos.',
        'Si un cartel indica que una función inicia a las 17:00 y dura 90 minutos, se puede deducir que termina a las 18:30.',
        [
          'Lee títulos, etiquetas, fechas y cantidades.',
          'Distingue los datos que ya están escritos.',
          'Relaciona dos o más datos mediante una operación.',
          'Expresa la nueva información con su unidad.',
        ],
      ),
      lesson(
        13,
        'En busca de información',
        'Información',
        'Selecciona fuentes y datos útiles para responder preguntas.',
        'Buscar información comienza con una pregunta clara. Después se elige una fuente apropiada y se separa lo relevante de los datos que no ayudan a responder.',
        'Para conocer el horario de una biblioteca sirven su cartel o calendario; el color del edificio no responde esa pregunta.',
        [
          'Formula exactamente lo que deseas saber.',
          'Elige una fuente donde probablemente esté la respuesta.',
          'Localiza palabras, números o símbolos relacionados.',
          'Comprueba que el dato responde la pregunta completa.',
        ],
      ),
    ],
  },
  {
    id: 2,
    numeral: 'II',
    label: 'Operaciones, orientación y medida',
    description:
      'Expresiones numéricas, multiplicación por decenas y centenas, croquis, puntos cardinales, longitudes y tablas.',
    goals: [
      'Comparar números escritos mediante expresiones aditivas y multiplicativas.',
      'Multiplicar dígitos por 10, 100 y sus múltiplos.',
      'Identificar los puntos cardinales.',
      'Comparar longitudes con distintos recursos.',
      'Distinguir información relevante en diversos portadores.',
    ],
    lessons: [
      lesson(
        14,
        '¿Cuál descomposición es mayor?',
        'Números',
        'Compara cantidades expresadas de distintas maneras.',
        'Una misma cantidad puede escribirse como suma de valores posicionales o como productos. Antes de comparar hay que obtener el valor total de cada expresión.',
        '3 × 1 000 + 5 × 100 + 8 = 3 508, que es mayor que 3 480.',
        [
          'Resuelve cada multiplicación.',
          'Suma los valores de cada expresión.',
          'Compara millares, centenas, decenas y unidades.',
          'Usa >, < o = para registrar el resultado.',
        ],
      ),
      lesson(
        15,
        '¿Se lee como se escribe?',
        'Números',
        'Relaciona nombres de números con su escritura en cifras.',
        'Al leer un número se consideran sus grupos de millares, centenas, decenas y unidades. Los ceros conservan la posición aunque no siempre se pronuncien.',
        '“Cuatro mil treinta y dos” se escribe 4 032: 4 millares, 0 centenas, 3 decenas y 2 unidades.',
        [
          'Separa el nombre del número por valores.',
          'Coloca cada cantidad en su posición.',
          'Usa cero donde no haya unidades de ese orden.',
          'Lee de nuevo el número para comprobarlo.',
        ],
      ),
      lesson(
        16,
        '¿Cuántos caben?',
        'Números',
        'Resuelve situaciones de agrupamiento.',
        'Cuando se quiere saber cuántos grupos iguales caben en una cantidad se puede restar repetidamente, formar grupos o dividir.',
        'En 24 fichas caben 6 grupos de 4 porque 4 + 4 + 4 + 4 + 4 + 4 = 24.',
        [
          'Identifica el total disponible.',
          'Determina el tamaño de cada grupo.',
          'Forma o resta grupos iguales.',
          'Cuenta los grupos y revisa si queda sobrante.',
        ],
      ),
      lesson(
        17,
        'Multipli… ¿qué?',
        'Números',
        'Reconoce distintos significados de la multiplicación.',
        'La multiplicación aparece en grupos iguales, arreglos rectangulares y combinaciones. Cambiar el orden de los factores no cambia el producto.',
        'Cuatro filas de 7 sillas forman 4 × 7 = 28; también pueden verse como 7 columnas de 4.',
        [
          'Localiza las dos cantidades que se relacionan.',
          'Decide qué representa cada factor.',
          'Calcula el producto.',
          'Explica el resultado con las unidades del problema.',
        ],
      ),
      lesson(
        18,
        '¿Multiplico por 10 o por 100?',
        'Números',
        'Usa estrategias rápidas para multiplicar por decenas y centenas.',
        'Multiplicar por 10 forma diez veces la cantidad y multiplicar por 100 forma cien veces la cantidad. Para 20 o 300 se multiplica primero por 2 o 3 y luego por 10 o 100.',
        '8 × 300 = 8 × 3 × 100 = 24 × 100 = 2 400.',
        [
          'Separa el múltiplo en un dígito y 10 o 100.',
          'Multiplica primero los dígitos.',
          'Multiplica el resultado por 10 o por 100.',
          'Comprueba estimando el tamaño del producto.',
        ],
      ),
      lesson(
        19,
        '¿Figura o cuerpo geométrico?',
        'Geometría',
        'Distingue figuras planas de cuerpos geométricos.',
        'Las figuras planas tienen largo y ancho; los cuerpos también tienen profundidad y ocupan espacio. Las caras de un cuerpo suelen tener forma de figuras planas.',
        'Un cuadrado es una figura plana; un cubo es un cuerpo cuyas seis caras son cuadrados.',
        [
          'Observa si el objeto tiene profundidad.',
          'Identifica sus caras o su contorno.',
          'Nombra las figuras planas presentes.',
          'Clasifica como figura o cuerpo y explica por qué.',
        ],
      ),
      lesson(
        20,
        'El croquis',
        'Geometría',
        'Lee y elabora croquis sencillos.',
        'Un croquis representa de manera aproximada un lugar y muestra rutas, referencias y símbolos sin necesitar una escala exacta.',
        'Para ir de la escuela a la tienda, el croquis puede indicar: avanza dos calles, gira a la derecha y cruza el parque.',
        [
          'Marca origen y destino.',
          'Ubica calles y puntos de referencia.',
          'Traza la ruta sin saltar cruces.',
          'Describe los movimientos en orden.',
        ],
      ),
      lesson(
        21,
        '¿Es norte o sur?',
        'Geometría',
        'Usa los puntos cardinales para orientarse.',
        'Norte, sur, este y oeste permiten comunicar direcciones. En muchos mapas el norte se coloca arriba; el sur abajo, el este a la derecha y el oeste a la izquierda.',
        'Si el museo está al este de la plaza, en un mapa orientado al norte aparecerá a su derecha.',
        [
          'Busca la rosa de los vientos o la orientación del mapa.',
          'Localiza el lugar de referencia.',
          'Observa hacia qué lado está el destino.',
          'Nombra el punto cardinal correspondiente.',
        ],
      ),
      lesson(
        22,
        '¿Qué tan largo es?',
        'Medición',
        'Compara longitudes mediante unidades y referencias.',
        'Medir significa comparar una longitud con una unidad. Para obtener resultados comparables se usa siempre la misma unidad y se coloca sin huecos ni traslapes.',
        'Si un lápiz cubre 15 clips iguales y otro 12, el primero mide 3 clips más.',
        [
          'Elige una unidad apropiada.',
          'Colócala desde el inicio del objeto.',
          'Repite la unidad sin dejar espacios.',
          'Cuenta y escribe el resultado con su unidad.',
        ],
      ),
      lesson(
        23,
        'Busca y mide objetos',
        'Medición',
        'Selecciona instrumentos y unidades para medir.',
        'La regla y el metro permiten medir con unidades convencionales. Los centímetros sirven para objetos pequeños y los metros para distancias mayores.',
        'Un cuaderno puede medir 27 cm de alto; un salón, cerca de 8 m de largo.',
        [
          'Estima primero la longitud.',
          'Elige centímetros o metros.',
          'Alinea el cero del instrumento con un extremo.',
          'Lee la marca final y compara con tu estimación.',
        ],
      ),
      lesson(
        24,
        'Mi identificación',
        'Información',
        'Reconoce datos relevantes en documentos personales.',
        'Una identificación organiza datos mediante etiquetas, números, fechas y fotografías. Cada dato responde una pregunta distinta y debe interpretarse en su contexto.',
        'La fecha de nacimiento permite calcular una edad; el número de registro distingue a personas con nombres parecidos.',
        [
          'Lee el nombre del documento.',
          'Ubica las etiquetas de cada campo.',
          'Selecciona solo el dato solicitado.',
          'Revisa formato y significado antes de responder.',
        ],
      ),
      lesson(
        25,
        'Tablas de datos',
        'Información',
        'Organiza e interpreta información en tablas.',
        'Las tablas usan filas y columnas para relacionar categorías y cantidades. El título y los encabezados indican qué representa cada dato.',
        'Si una tabla registra 12 votos para rojo y 8 para azul, rojo tiene 4 votos más.',
        [
          'Lee título y encabezados.',
          'Localiza el cruce de fila y columna adecuado.',
          'Compara o combina los datos necesarios.',
          'Redacta la conclusión con su categoría y cantidad.',
        ],
      ),
    ],
  },
  {
    id: 3,
    numeral: 'III',
    label: 'Fracciones, algoritmos y simetría',
    description:
      'Fracciones con medios, cuartos y octavos; multiplicación, división, simetría, cuadrículas y organización de datos.',
    goals: [
      'Resolver repartos cuyo resultado sea una fracción con denominador 2, 4 u 8.',
      'Multiplicar números de tres cifras por un dígito.',
      'Resolver divisiones mediante diversos procedimientos.',
      'Identificar ejes de simetría.',
      'Reproducir figuras usando una cuadrícula.',
    ],
    lessons: [
      lesson(
        26,
        'La mitad de la mitad de la mitad',
        'Números',
        'Construye medios, cuartos y octavos mediante particiones iguales.',
        'Una fracción representa partes iguales de un todo. La mitad de una mitad es un cuarto y la mitad de un cuarto es un octavo.',
        'Si una hoja se parte en 2, luego cada parte en 2 y otra vez en 2, se obtienen 8 partes iguales; cada una es 1/8.',
        [
          'Define cuál es el entero.',
          'Divídelo en dos partes iguales.',
          'Vuelve a dividir cada parte por la mitad.',
          'Cuenta las partes iguales y escribe la fracción.',
        ],
      ),
      lesson(
        27,
        '¿Cuánto queda?',
        'Números',
        'Calcula la parte restante de una unidad.',
        'Para saber cuánto queda, se representa el entero con todas sus partes iguales y se restan las partes usadas. El denominador permanece igual cuando las partes tienen el mismo tamaño.',
        'De una barra dividida en 8 partes se comen 3: quedan 8/8 - 3/8 = 5/8.',
        [
          'Representa el entero como una fracción completa.',
          'Identifica cuántas partes se utilizaron.',
          'Resta los numeradores.',
          'Conserva el denominador y verifica en el dibujo.',
        ],
      ),
      lesson(
        28,
        '¡A buscar el número que falta!',
        'Números',
        'Encuentra términos desconocidos usando operaciones inversas.',
        'Cuando falta un número en una igualdad, una operación inversa ayuda a encontrarlo: suma y resta se deshacen entre sí; multiplicación y división también.',
        'En 7 + □ = 15, el número faltante es 15 - 7 = 8.',
        [
          'Identifica qué dato falta.',
          'Observa la operación y el resultado.',
          'Aplica la operación inversa.',
          'Sustituye el número y comprueba la igualdad.',
        ],
      ),
      lesson(
        29,
        '¿Cómo multiplico?',
        'Números',
        'Multiplica números de varias cifras por un dígito.',
        'El algoritmo multiplica de derecha a izquierda, comenzando por unidades. Cuando un producto supera 9, se escriben las unidades y se reagrupan las decenas.',
        'Para 326 × 4: 4×6=24; se escribe 4 y van 2. 4×2+2=10; se escribe 0 y va 1. 4×3+1=13. Resultado: 1 304.',
        [
          'Alinea el factor bajo las unidades.',
          'Multiplica las unidades y reagrupa si hace falta.',
          'Continúa con decenas y centenas.',
          'Comprueba mediante estimación o descomposición.',
        ],
      ),
      lesson(
        30,
        '¿Cuántos duraznos reparto en cada bolsa?',
        'Números',
        'Interpreta la división como reparto equitativo.',
        'Dividir permite repartir una cantidad en grupos iguales. El cociente indica cuánto recibe cada grupo y el residuo lo que no puede repartirse por igual.',
        'Al repartir 26 duraznos en 4 bolsas, cada bolsa recibe 6 y sobran 2: 26 = 4 × 6 + 2.',
        [
          'Representa el total.',
          'Forma el número de grupos indicado.',
          'Reparte uno a uno o en tandas iguales.',
          'Cuenta cada grupo y registra el sobrante.',
        ],
      ),
      lesson(
        31,
        'Los ejes de simetría',
        'Geometría',
        'Identifica líneas que dividen figuras en partes reflejadas.',
        'Un eje de simetría divide una figura en dos partes que coinciden al doblarla. Algunas figuras tienen varios ejes y otras ninguno.',
        'Un cuadrado tiene 4 ejes de simetría: dos medianas y dos diagonales.',
        [
          'Imagina o realiza un doblez.',
          'Compara puntos a ambos lados de la línea.',
          'Comprueba que estén a igual distancia.',
          'Cuenta todas las líneas que producen coincidencia.',
        ],
      ),
      lesson(
        32,
        'Cuadrículas y figuras',
        'Geometría',
        'Reproduce figuras conservando posiciones y proporciones.',
        'La cuadrícula funciona como sistema de referencia. Para copiar una figura se cuenta el desplazamiento entre puntos y se conserva su posición respecto a filas y columnas.',
        'Si un vértice está 3 cuadros a la derecha y 2 arriba del anterior, la copia debe repetir exactamente ese recorrido.',
        [
          'Elige un punto inicial fácil de localizar.',
          'Cuenta cuadros horizontales y verticales.',
          'Marca cada vértice en la nueva cuadrícula.',
          'Une los puntos y compara la figura completa.',
        ],
      ),
      lesson(
        33,
        '¿Aproximadamente cuánto mide esa superficie?',
        'Medición',
        'Estima áreas usando unidades cuadradas.',
        'El área expresa cuánto espacio cubre una superficie. Puede estimarse contando cuadrados completos y reuniendo partes de cuadrados.',
        'Una figura cubre 18 cuadros completos y dos medios cuadros: su área aproximada es 19 unidades cuadradas.',
        [
          'Elige una unidad cuadrada.',
          'Cuenta los cuadros completos cubiertos.',
          'Reúne fracciones de cuadro para formar enteros.',
          'Expresa el resultado como aproximación.',
        ],
      ),
      lesson(
        34,
        '¿Cómo se organiza la información?',
        'Información',
        'Elige formas claras de registrar y comparar datos.',
        'Una lista de datos se entiende mejor al agrupar valores iguales y registrar sus frecuencias en una tabla. Así se identifican rápidamente el mayor, el menor y el más frecuente.',
        'En 2, 3, 2, 4, 2, el número 2 aparece tres veces; su frecuencia es 3.',
        [
          'Define las categorías.',
          'Cuenta cuántas veces aparece cada una.',
          'Registra las frecuencias en una tabla.',
          'Verifica que la suma coincida con el total de datos.',
        ],
      ),
    ],
  },
  {
    id: 4,
    numeral: 'IV',
    label: 'Fracciones, reparto y ubicación',
    description:
      'Equivalencias, operaciones, multiplicación, división, giros, referencias espaciales, medida y tablas.',
    goals: [
      'Identificar escrituras equivalentes con fracciones.',
      'Resolver problemas mediante distintas operaciones.',
      'Usar la división en repartos y agrupamientos.',
      'Ubicar objetos con diferentes puntos de referencia.',
      'Obtener información de tablas y reconocer eventos previsibles.',
    ],
    lessons: [
      lesson(
        35,
        'Comparemos fracciones',
        'Números',
        'Compara fracciones y reconoce equivalencias.',
        'Las fracciones son comparables cuando se refieren al mismo entero. Partes con nombres distintos pueden cubrir la misma cantidad.',
        'Una mitad equivale a dos cuartos: 1/2 = 2/4. En cambio, 3/4 es mayor porque cubre una parte adicional.',
        [
          'Confirma que los enteros tengan el mismo tamaño.',
          'Representa ambas fracciones.',
          'Busca particiones del mismo tamaño.',
          'Compara las partes cubiertas y usa >, < o =.',
        ],
      ),
      lesson(
        36,
        'Con diferentes operaciones',
        'Números',
        'Elige la operación adecuada para cada problema.',
        'La situación indica la operación: juntar o aumentar sugiere suma; quitar o comparar, resta; formar grupos iguales, multiplicación; repartir o agrupar, división.',
        'Si hay 6 mesas con 4 estudiantes y llegan 3 más: 6 × 4 + 3 = 27 estudiantes.',
        [
          'Identifica qué se conoce y qué se pregunta.',
          'Relaciona cada acción con una operación.',
          'Resuelve respetando el orden de la situación.',
          'Comprueba si el resultado tiene sentido.',
        ],
      ),
      lesson(
        37,
        'Multiplico hasta centenas',
        'Números',
        'Resuelve multiplicaciones con centenas.',
        'Los números de tres cifras pueden descomponerse en centenas, decenas y unidades para multiplicar cada parte por el mismo factor.',
        '214 × 3 = 200×3 + 10×3 + 4×3 = 600 + 30 + 12 = 642.',
        [
          'Descompón el número por valor posicional.',
          'Multiplica cada parte.',
          'Suma los productos parciales.',
          'Verifica con el algoritmo convencional.',
        ],
      ),
      lesson(
        38,
        'Practiquemos la división',
        'Números',
        'Resuelve divisiones por reparto y agrupamiento.',
        'En un reparto se pregunta cuánto toca a cada grupo; en un agrupamiento, cuántos grupos se pueden formar. Ambos se representan con una división.',
        '35 ÷ 5 = 7 porque 5 × 7 = 35.',
        [
          'Determina si repartirás o formarás grupos.',
          'Usa dibujos, restas repetidas o productos conocidos.',
          'Encuentra el cociente y, si existe, el residuo.',
          'Comprueba multiplicando divisor por cociente.',
        ],
      ),
      lesson(
        39,
        'Giros y ángulos',
        'Geometría',
        'Reconoce giros completos, medios y cuartos de vuelta.',
        'Un giro cambia la orientación. Una vuelta completa regresa al inicio; media vuelta cambia al sentido opuesto y un cuarto de vuelta forma un ángulo recto.',
        'Si una flecha apunta al norte y gira un cuarto de vuelta a la derecha, termina apuntando al este.',
        [
          'Marca la orientación inicial.',
          'Identifica el sentido del giro.',
          'Divide la vuelta en cuartos si es necesario.',
          'Dibuja y nombra la orientación final.',
        ],
      ),
      lesson(
        40,
        '¿En dónde se encuentra?',
        'Geometría',
        'Describe posiciones usando referencias.',
        'La ubicación depende del punto de referencia. Expresiones como derecha, izquierda, delante, detrás y entre deben indicar respecto de qué objeto se usan.',
        'El vaso puede estar a la izquierda del plato desde la posición de quien está sentado frente a la mesa.',
        [
          'Elige un punto de referencia.',
          'Define desde dónde se observa.',
          'Compara la posición del objeto.',
          'Describe la ubicación sin ambigüedad.',
        ],
      ),
      lesson(
        41,
        'Mido ingredientes',
        'Medición',
        'Interpreta unidades de masa y capacidad en recetas.',
        'Las recetas combinan cantidades y unidades. Kilogramo y gramo miden masa; litro y mililitro miden capacidad. Medios y cuartos permiten expresar porciones.',
        'Dos paquetes de 1/4 kg reúnen 1/2 kg; cuatro paquetes reúnen 1 kg.',
        [
          'Identifica la unidad usada.',
          'Representa cada porción como fracción.',
          'Reúne porciones equivalentes.',
          'Expresa el total con la misma unidad.',
        ],
      ),
      lesson(
        42,
        'La tabla de Pitágoras',
        'Información',
        'Usa la tabla para encontrar productos y reconocer patrones.',
        'La tabla de Pitágoras organiza los productos de dos factores. Como 4 × 7 y 7 × 4 son iguales, la tabla es simétrica respecto de su diagonal.',
        'Para encontrar 6 × 8, cruza la fila del 6 con la columna del 8: el resultado es 48.',
        [
          'Ubica un factor en una fila.',
          'Ubica el otro en una columna.',
          'Encuentra la casilla donde se cruzan.',
          'Observa relaciones con dobles, mitades y productos vecinos.',
        ],
      ),
    ],
  },
  {
    id: 5,
    numeral: 'V',
    label: 'Fracciones, cálculo y azar',
    description:
      'Representación de fracciones, división, estimación, cálculo mental, cuadrículas, unidades y registro de juegos de azar.',
    goals: [
      'Representar gráficamente fracciones.',
      'Anticipar cambios en el resultado de una división.',
      'Resolver sumas y restas sencillas de fracciones.',
      'Calcular mentalmente divisiones simples.',
      'Identificar juegos de azar y registrar resultados.',
    ],
    lessons: [
      lesson(
        43,
        'La huerta en fracciones',
        'Números',
        'Representa partes de una región mediante fracciones.',
        'Para representar una fracción, el entero se divide en partes de igual área. El denominador indica todas las partes y el numerador las seleccionadas.',
        'Si una huerta tiene 8 parcelas iguales y 3 tienen zanahoria, las zanahorias ocupan 3/8.',
        [
          'Define la huerta completa como entero.',
          'Cuenta todas las parcelas iguales.',
          'Cuenta las parcelas de la categoría.',
          'Escribe numerador sobre denominador.',
        ],
      ),
      lesson(
        44,
        'Partir y compartir',
        'Números',
        'Analiza cómo cambia el resultado de una división.',
        'Si el total aumenta y el número de grupos permanece, cada parte aumenta. Si aumentan los grupos y el total permanece, cada parte disminuye.',
        '24 galletas entre 4 niños dan 6 a cada uno; entre 8 niños dan 3.',
        [
          'Identifica dividendo y divisor.',
          'Decide cuál cantidad cambió.',
          'Anticipa si el cociente crecerá o disminuirá.',
          'Calcula y compara para confirmar.',
        ],
      ),
      lesson(
        45,
        'Cerca de 10, 100 o 1 000',
        'Números',
        'Estima resultados usando números cercanos.',
        'Redondear permite calcular aproximadamente. Se elige un número cercano que sea fácil de operar y después se valora si el resultado exacto será mayor o menor.',
        '398 + 205 está cerca de 400 + 200 = 600; el resultado exacto es 603.',
        [
          'Identifica el orden de magnitud.',
          'Sustituye por decenas, centenas o millares cercanos.',
          'Realiza la operación sencilla.',
          'Compara la estimación con el cálculo exacto.',
        ],
      ),
      lesson(
        46,
        'Sumar las partes de un todo',
        'Números',
        'Suma y resta fracciones con el mismo denominador.',
        'Cuando las partes son del mismo tamaño se suman o restan los numeradores; el denominador no cambia porque conserva el tamaño de cada parte.',
        '2/8 + 3/8 = 5/8. Si se usa 1/8, quedan 4/8.',
        [
          'Verifica que los denominadores sean iguales.',
          'Suma o resta los numeradores.',
          'Conserva el denominador.',
          'Representa el resultado para comprobar.',
        ],
      ),
      lesson(
        47,
        '¿Cuántas veces?',
        'Números',
        'Resuelve divisiones simples mediante productos conocidos.',
        'Dividir puede significar averiguar cuántas veces cabe una cantidad en otra. Las tablas de multiplicar permiten encontrar rápidamente el cociente.',
        'Para 42 ÷ 6 se pregunta: ¿6 por cuánto da 42? Como 6 × 7 = 42, el cociente es 7.',
        [
          'Expresa la división como una pregunta de multiplicación.',
          'Busca el producto en una tabla conocida.',
          'Escribe el factor faltante como cociente.',
          'Comprueba multiplicando.',
        ],
      ),
      lesson(
        48,
        'La técnica de los griegos',
        'Números',
        'Explora una estrategia gráfica de multiplicación.',
        'Una multiplicación puede resolverse descomponiendo los factores y organizando productos parciales en una cuadrícula. Todas las partes deben reunirse al final.',
        '23 × 14 = 20×10 + 20×4 + 3×10 + 3×4 = 200 + 80 + 30 + 12 = 322.',
        [
          'Descompón ambos factores.',
          'Traza una cuadrícula para combinar cada parte.',
          'Calcula todos los productos parciales.',
          'Súmalos sin omitir ninguna región.',
        ],
      ),
      lesson(
        49,
        'El mar en cuadrícula',
        'Geometría',
        'Ubica y reproduce trayectos usando una cuadrícula.',
        'Las filas y columnas permiten indicar posiciones con precisión. Un recorrido se describe contando casillas y señalando la dirección de cada movimiento.',
        'Desde una casilla inicial: 4 a la derecha y 2 arriba determinan una nueva posición única.',
        [
          'Marca el punto inicial.',
          'Lee cada desplazamiento en orden.',
          'Cuenta casillas sin incluir la de salida.',
          'Marca el destino y revisa el recorrido.',
        ],
      ),
      lesson(
        50,
        'Estimo y comparo unidades',
        'Medición',
        'Elige unidades adecuadas y compara mediciones.',
        'Una unidad debe corresponder con lo que se mide y con el tamaño del objeto. Estimar antes de medir ayuda a detectar resultados poco razonables.',
        'Es razonable medir una puerta en metros y el grosor de un lápiz en milímetros o centímetros, no al revés.',
        [
          'Identifica la magnitud: longitud, masa o capacidad.',
          'Elige una unidad adecuada.',
          'Haz una estimación.',
          'Mide o compara y explica la diferencia.',
        ],
      ),
      lesson(
        51,
        'Registra al ganador',
        'Información',
        'Registra resultados y determina frecuencias.',
        'En un juego, una tabla de conteo evita perder datos. Cada marca representa un resultado y la frecuencia total permite identificar al ganador.',
        'Si Ana obtiene 7 marcas, Luis 5 y Eva 6, Ana gana porque tiene la frecuencia mayor.',
        [
          'Define una fila para cada participante o resultado.',
          'Añade una marca en cada turno.',
          'Cuenta las marcas al finalizar.',
          'Compara totales y declara el resultado.',
        ],
      ),
      lesson(
        52,
        'Lanza un dado',
        'Azar',
        'Reconoce resultados posibles en experimentos aleatorios.',
        'En un juego de azar no se conoce de antemano el resultado de cada intento, aunque sí pueden enumerarse los resultados posibles y registrar qué tan seguido ocurren.',
        'Al lanzar un dado, los resultados posibles son 1, 2, 3, 4, 5 y 6; ninguno está garantizado en un lanzamiento.',
        [
          'Enumera todos los resultados posibles.',
          'Realiza varios intentos en condiciones iguales.',
          'Registra cada resultado en una tabla.',
          'Compara frecuencias sin asegurar qué ocurrirá después.',
        ],
      ),
    ],
  },
];

export const allLessons = bookBlocks.flatMap((block) =>
  block.lessons.map((item) => ({ ...item, blockId: block.id })),
);
